# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('my_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clickevent', to='shortener.MyShortURL')),
            ],
        ),
    ]
